# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"
add_newline = true

[directory]
truncation_length = 1

[time]
disabled = true
style = "bold bright-black"
format = "[$time]($style)"

[line_break]
# disabled = true
disabled = false

# Replace the '❯' symbol in the prompt with '➜' '✘'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](bold green)"
error_symbol = "[✘](bold red)"
#success_symbol = "[❯](bold green)"
#error_symbol = "[❯](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true


